<?php

/* 
 * Copyright (C) 2014 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$form = $this->form;
$form->prepare();
$form->setAttribute('action', call_user_func($this->route_builder, 'edit', $this->id, $this->alias));
$form->setAttribute('method', 'post');
?>

<h1><?php echo $this->translate($this->title) ?></h1>

<?php echo $this->partial('partial/admin_form.phtml', array('formular' => $form)); ?>

<a href="<?php echo call_user_func($this->route_builder, 'delete', $this->id, $this->alias) ; ?>"
   onclick="return confirm('<?php echo $this->translate($this->delete_warning_text) ?>')">
    <?php echo $this->translate('Delete') ?>
</a>