<?php

/* 
 * Copyright (C) 2015 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

if ($this->pageCount): ?>
<div class="pagination pagination-centered pagination-small">
    <ul class="pagination">

        <!-- First page link -->
        <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo call_user_func($this->route_builder, 'list', $this->first); ?>">&lt;&lt; <?= $this->translate('First'); ?></a>
        </li>

        <!-- Previous page link -->
        <li<?php echo (isset($this->previous)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo call_user_func($this->route_builder, 'list', $this->previous-9); ?>">&lt; <?= $this->translate('Previous 10'); ?></a>
        </li>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        <li<?php echo ($page == $this->current) ? ' class="active"' : ''; ?>>
            <a href="<?php echo call_user_func($this->route_builder, 'list', $page); ?>"><?php echo $page; ?></a>
        </li>
        <?php endforeach; ?>

        <!-- Next page link -->
        <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo call_user_func($this->route_builder, 'list', $this->next+9); ?>"><?= $this->translate('Next 10'); ?> &gt;</a>
        </li>

        <!-- Last page link -->
        <li<?php echo (isset($this->next)) ? '' : ' class="disabled"'; ?>>
            <a href="<?php echo call_user_func($this->route_builder, 'list', $this->last); ?>"><?= $this->translate('Last'); ?> &gt;&gt;</a>
        </li>

    </ul>
</div>
<?php endif; ?>

<?php
$script = $this->inlineScript();
$script->appendScript(<<<'EOT'
    
$(".pagination .disabled a").click(function() {
  return false;
});

EOT
);
